all:
  vars:
    control_plane_endpoint: 192.168.1.100
    load_balancer_ip_pool:
      - 192.168.1.224/27
metal:
  children:
    masters:
      hosts:
        prox1:
          {
            ansible_host: 192.168.1.110,
            mac: "bc:24:11:71:1a:37",
            disk: sda,
            network_interface: eth0,
          }
        prox2:
          {
            ansible_host: 192.168.1.111,
            mac: "bc:24:11:22:f1:47",
            disk: sda,
            network_interface: eth0,
          }
        prox3:
          {
            ansible_host: 192.168.1.112,
            mac: "bc:24:11:86:b2:40",
            disk: sda,
            network_interface: eth0,
          }
    workers:
      hosts:
        prox4:
          {
            ansible_host: 192.168.1.113,
            mac: "bc:24:11:3e:ea:e7",
            disk: sda,
            network_interface: eth0,
          }
        prox5:
          {
            ansible_host: 192.168.1.114,
            mac: "bc:24:11:b1:bc:a6",
            disk: sda,
            network_interface: eth0,
          }
        prox6:
          {
            ansible_host: 192.168.1.115,
            mac: "bc:24:11:6f:8d:08",
            disk: sda,
            network_interface: eth0,
          }
